// Worker helpers with no Cloudflare-specific types: limits, room-code handling,
// request validation, and the tolerant parser for the model's gloss output.
//
// They live in their own file for one reason: everything else under src/worker/
// refers to Workers-only ambient types (Ai, Fetcher, DurableObjectState), which
// the browser/test tsconfig does not load. Keeping these here means the rules
// that reject bad input and read model output are unit-tested rather than only
// exercised by hand.

import type { VocabSet, QuizQuestion, Level, RoomModel } from '../shared/types';

// --- limits ------------------------------------------------------------------

// Structural limits (shape of the data). Cost limits, and anything an operator
// may want to retune without a deploy, live in ./policy.ts instead.
export const MAX_SET_ITEMS = 200;
export const MAX_NAME_CHARS = 24;
/** Player ids are generated by newId(); the cap only keeps junk out of the DO. */
export const MAX_PLAYER_ID_CHARS = 64;
/** A host key is a crypto.randomUUID() (36 chars); the cap is the same courtesy. */
export const MAX_HOST_KEY_CHARS = 64;
/** A member key is a crypto.randomUUID() too. */
export const MAX_MEMBER_KEY_CHARS = 64;
/** One question per item per direction, so at most 2x the item cap. */
export const MAX_QUESTIONS = MAX_SET_ITEMS * 2;
export const MAX_ZH_CHARS = 40;
export const MAX_ID_CHARS = 64;
/** buildQuestions makes one correct label plus at most three distractors. */
export const MAX_CHOICES = 4;
export const TTS_MAX_CHARS = 60;

// --- room codes --------------------------------------------------------------

/** Unambiguous alphabet: no O/0, no I/1, no letters that look alike on a projector. */
export const CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
export const CODE_LENGTH = 4;

export function generateCode(): string {
  const bytes = new Uint8Array(CODE_LENGTH);
  crypto.getRandomValues(bytes);
  let code = '';
  for (const b of bytes) code += CODE_ALPHABET[b % CODE_ALPHABET.length];
  return code;
}

export function isValidCode(code: string): boolean {
  if (code.length !== CODE_LENGTH) return false;
  for (const ch of code) if (!CODE_ALPHABET.includes(ch)) return false;
  return true;
}

// --- Chinese text ------------------------------------------------------------

/** CJK Unified Ideographs, Extension A, and the compatibility block. */
const CJK_CHAR = /[㐀-䶿一-鿿豈-﫿]/;
/** CJK punctuation, fullwidth forms, curly quotes, and whitespace. */
const CJK_PUNCT_OR_SPACE = /[\s　-〿！-～‘’“”]/;

/**
 * True only for Chinese text: at least one CJK ideograph, and every other
 * character is CJK punctuation or whitespace. An English phrase is rejected,
 * because the browser can already speak that with its own voice.
 */
export function isChineseText(text: string): boolean {
  if (!text) return false;
  let sawCjk = false;
  for (const ch of text) {
    if (CJK_CHAR.test(ch)) {
      sawCjk = true;
      continue;
    }
    if (CJK_PUNCT_OR_SPACE.test(ch)) continue;
    return false;
  }
  return sawCjk;
}

/**
 * True when the text holds at least one CJK ideograph, whatever else is in it.
 * Looser than isChineseText on purpose: the enrich route only needs to know
 * that a row is a Chinese word and not a paragraph of English somebody is
 * using the endpoint to translate for free.
 */
export function containsCjk(text: string): boolean {
  for (const ch of text) if (CJK_CHAR.test(ch)) return true;
  return false;
}

// --- model output ------------------------------------------------------------

export interface GlossPair {
  zh: string;
  en: string;
}

/**
 * Pulls a JSON array of {zh, en} out of a model response.
 *
 * Workers AI hands this back in two different shapes depending on the model and
 * the day: sometimes an already-parsed array, sometimes a string that may be
 * wrapped in a ```json fence, prefixed with chatter, or followed by trailing
 * text. Both are handled. Returns an empty array when nothing usable is found,
 * and never throws.
 */
export function parseGlossArray(raw: unknown): GlossPair[] {
  if (Array.isArray(raw)) return collectPairs(raw);
  if (typeof raw !== 'string') return [];

  let text = raw.trim();

  // Prefer the contents of a code fence when one is present.
  const fence = text.match(/```(?:json|JSON)?\s*([\s\S]*?)```/);
  if (fence) text = fence[1].trim();

  // Take the outermost bracketed array, tolerating text on either side.
  const first = text.indexOf('[');
  const last = text.lastIndexOf(']');
  if (first === -1 || last === -1 || last <= first) return [];

  let parsed: unknown;
  try {
    parsed = JSON.parse(text.slice(first, last + 1));
  } catch {
    return [];
  }
  if (!Array.isArray(parsed)) return [];
  return collectPairs(parsed);
}

function collectPairs(entries: unknown[]): GlossPair[] {
  const out: GlossPair[] = [];
  for (const entry of entries) {
    if (!entry || typeof entry !== 'object') continue;
    const rec = entry as Record<string, unknown>;
    const zh = typeof rec.zh === 'string' ? rec.zh.trim() : '';
    const en = typeof rec.en === 'string' ? rec.en.trim() : '';
    if (!zh) continue;
    out.push({ zh, en });
  }
  return out;
}

// --- request validation ------------------------------------------------------

function isNonEmptyString(v: unknown, max: number): v is string {
  return typeof v === 'string' && v.trim().length > 0 && v.length <= max;
}

/** Returns a human-readable error message, or null when the set is usable. */
export function validateSet(value: unknown): string | null {
  if (!value || typeof value !== 'object') return 'set must be an object';
  const set = value as Partial<VocabSet>;
  if (set.v !== 1) return 'set.v must be 1';
  if (typeof set.title !== 'string' || set.title.length > 200) return 'set.title must be a string';
  const levels: Level[] = ['kids', 'big'];
  if (!levels.includes(set.level as Level)) return "set.level must be 'kids' or 'big'";
  if (!Array.isArray(set.items)) return 'set.items must be an array';
  if (set.items.length === 0) return 'set.items must not be empty';
  if (set.items.length > MAX_SET_ITEMS) return `set.items must have at most ${MAX_SET_ITEMS} items`;
  for (const item of set.items) {
    if (!item || typeof item !== 'object') return 'each set item must be an object';
    const it = item as unknown as Record<string, unknown>;
    if (!isNonEmptyString(it.id, MAX_ID_CHARS)) return 'each set item needs an id';
    if (!isNonEmptyString(it.zh, MAX_ZH_CHARS)) return 'each set item needs a zh word';
    if (typeof it.pinyin !== 'string' || it.pinyin.length > 200) return 'pinyin must be a string';
    if (typeof it.en !== 'string' || it.en.length > 200) return 'en must be a string';
  }
  return null;
}

/**
 * Returns a human-readable error message, or null when the questions are usable.
 *
 * Checked against the set they claim to belong to, not in isolation: a client
 * could otherwise create a room whose questions point at nothing, hold a wrong
 * answer key, repeat a choice label, or arrive out of order. `index` must be
 * exactly the position in the array, because that is the ordinal the answer
 * route and the race schedule both use.
 */
export function validateQuestions(value: unknown, set: VocabSet): string | null {
  if (!Array.isArray(value)) return 'questions must be an array';
  if (value.length === 0) return 'questions must not be empty';
  if (value.length > MAX_QUESTIONS) return `questions must have at most ${MAX_QUESTIONS} entries`;

  const byId = new Map(set.items.map((item) => [item.id, item]));

  for (let position = 0; position < value.length; position++) {
    const q = value[position];
    if (!q || typeof q !== 'object') return 'each question must be an object';
    const qq = q as Partial<QuizQuestion>;

    if (!Number.isInteger(qq.index) || qq.index !== position) {
      return 'question.index must run 0, 1, 2 ... in order';
    }
    if (qq.dir !== 'zh2en' && qq.dir !== 'en2zh') return 'question.dir must be zh2en or en2zh';
    if (!isNonEmptyString(qq.itemId, MAX_ID_CHARS)) {
      return `each question needs an itemId of at most ${MAX_ID_CHARS} characters`;
    }
    const item = byId.get(qq.itemId);
    if (!item) return 'each question must point at an item in the set';
    if (typeof qq.prompt !== 'string' || qq.prompt.length > 200) return 'question.prompt too long';
    if (
      !Array.isArray(qq.choices) ||
      qq.choices.length < 2 ||
      qq.choices.length > MAX_CHOICES
    ) {
      return `question.choices must have 2 to ${MAX_CHOICES} entries`;
    }
    if (qq.choices.some((c) => typeof c !== 'string' || c.length > 200)) {
      return 'question.choices must be short strings';
    }
    if (new Set(qq.choices).size !== qq.choices.length) {
      return 'question.choices must not repeat a label';
    }
    if (
      typeof qq.answer !== 'number' ||
      !Number.isInteger(qq.answer) ||
      qq.answer < 0 ||
      qq.answer >= qq.choices.length
    ) {
      return 'question.answer must index into question.choices';
    }
    const expected = qq.dir === 'zh2en' ? item.en : item.zh;
    if (qq.choices[qq.answer] !== expected) {
      return 'question.answer must point at the right word for that item';
    }
  }
  return null;
}

/** Returns a message, or null when the enrich payload is usable. */
export function validateEnrichItems(value: unknown, maxItems: number): string | null {
  if (!Array.isArray(value)) return 'items must be an array';
  if (value.length === 0) return 'items must not be empty';
  if (value.length > maxItems) return `at most ${maxItems} items per request`;
  for (const item of value) {
    if (!item || typeof item !== 'object') return 'each item must be an object';
    const it = item as Record<string, unknown>;
    if (!isNonEmptyString(it.zh, MAX_ZH_CHARS)) {
      return `each item needs a zh word of at most ${MAX_ZH_CHARS} characters`;
    }
    if (!containsCjk(it.zh)) return 'every word must be Chinese';
    if (it.en !== undefined && (typeof it.en !== 'string' || it.en.length > 200)) {
      return 'en must be a short string when present';
    }
  }
  return null;
}

// --- room action authorization ------------------------------------------------

/**
 * Which credential a room action needs (plan amendment 8).
 *
 * `join` is how you GET a playerId, so it needs neither. `round`, `end`,
 * `lobby` and `close` are the teacher's controls, and she is not a player, so
 * they take a host key OR the legacy player-host's id. `answer`, `pick` and `start` are
 * things a player does and always need a playerId.
 *
 * Requiring a playerId on every non-join action, which is what v1 did, would
 * lock a teacher out of her own room.
 */
export type RoomActionAuth = 'none' | 'host' | 'player' | 'unknown';

export function roomActionAuthFor(action: string): RoomActionAuth {
  if (action === 'join') return 'none';
  if (
    action === 'round' ||
    action === 'end' ||
    action === 'lobby' ||
    action === 'close' ||
    // The projector asking what the right answer was. Host only: the answer
    // key must never reach a student device (D3).
    action === 'reveal'
  ) {
    return 'host';
  }
  if (action === 'start' || action === 'answer' || action === 'pick') return 'player';
  return 'unknown';
}

/**
 * Is this caller the host of this room?
 *
 * Two ways in, never more: the teacher's host key (which lives in its own DO
 * storage slot and is never part of RoomState, so it cannot leak through
 * publicState), or the legacy "Race a friend" host, who is the first joiner.
 *
 * An empty stored key, an empty hostId, or an empty credential never matches, so
 * a caller cannot authorize themselves by sending nothing.
 */
export function isHostAuthorized(opts: {
  hostKey?: unknown;
  playerId?: unknown;
  storedHostKey?: string;
  hostId: string;
}): boolean {
  const hostKey = typeof opts.hostKey === 'string' ? opts.hostKey : '';
  if (hostKey && opts.storedHostKey && hostKey === opts.storedHostKey) return true;
  const playerId = typeof opts.playerId === 'string' ? opts.playerId : '';
  return playerId !== '' && opts.hostId !== '' && playerId === opts.hostId;
}

/**
 * Is this caller allowed to ask what the right answer was?
 *
 * Stricter than `isHostAuthorized` on purpose, and the one host action that is.
 * The generic gate also accepts the legacy "Race a friend" host, who is simply
 * the first joiner, and that id travels in `publicState` where the OTHER player
 * reads it off their own poll and can replay it. For the teacher's controls
 * that costs a legacy room nothing (the pair are already both hosts in spirit),
 * but `reveal` hands back an answer key, so it takes the private host key that
 * was minted once at create and never appears on the wire, or nothing.
 *
 * A legacy room has no projector, so nothing real loses this route.
 *
 * `playerId` is in the signature and deliberately unread: it is what a caller
 * sends, and the type is the place to say that sending it achieves nothing.
 */
export function isRevealAuthorized(opts: {
  hostKey?: unknown;
  playerId?: unknown;
  storedHostKey?: string;
}): boolean {
  const hostKey = typeof opts.hostKey === 'string' ? opts.hostKey : '';
  const stored = typeof opts.storedHostKey === 'string' ? opts.storedHostKey : '';
  return hostKey !== '' && stored !== '' && hostKey === stored;
}

/** What a player is told when their member key does not match. Plain language. */
export const NOT_A_MEMBER =
  'this device is not signed in to this game, please join again with the room code';

/**
 * Is this caller really the player they say they are?
 *
 * `players` is PUBLIC: every device in the room can read every player id off the
 * scoreboard. A player id is therefore a name badge, and week 2 was using it as
 * a password, so any student could answer as another student or burn their
 * Treasure Dash chest (Codex round 1, MUST-FIX 2). The real credential is
 * `memberKey`, handed out once by `join` and kept in its own storage slot.
 *
 * The one exemption is a `model: 1` room. A week-1 client has no member key and
 * no way to get one, so a race running across the deploy would die mid-question.
 * A v1 room is a two-person "Race a friend" room whose players already have the
 * whole set locally, so the id-alone path costs nothing there. A model 2 room
 * NEVER takes an id alone: no stored key, no action.
 */
export function isMemberAuthorized(opts: {
  model: RoomModel;
  playerId?: unknown;
  memberKey?: unknown;
  storedMemberKey?: string;
}): boolean {
  const playerId = typeof opts.playerId === 'string' ? opts.playerId : '';
  if (playerId === '') return false;
  if (opts.model === 1) return true;

  const memberKey = typeof opts.memberKey === 'string' ? opts.memberKey : '';
  const stored = opts.storedMemberKey ?? '';
  // An empty key never matches an empty stored key: a room that has lost its
  // members map must refuse everyone rather than accept anyone.
  return memberKey !== '' && stored !== '' && memberKey === stored;
}

